os:
    - windows
language: node_js
node_js:
    - "10"
before_install:
    - npm install -g node-gyp
install:
    - npm ci --only=production
    - node-gyp configure
    - node-gyp build
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
